/**
 * Maps ticker symbols and common abbreviations to search terms that appear in
 * NSE RSS feed titles. Each key is what a user might type; values are
 * lowercase substrings checked against the feed item title/content (OR logic).
 *
 * Coverage: NSE 500 constituents + common short-forms.
 */
export const COMPANY_ALIASES: Record<string, string[]> = {
  // ── Nifty 50 ──────────────────────────────────────────────────────────────
  reliance:       ["reliance industries", "reliance"],
  ril:            ["reliance industries", "ril"],
  tcs:            ["tata consultancy", "tcs"],
  hdfcbank:       ["hdfc bank"],
  hdfc:           ["hdfc"],
  bhartiartl:     ["bharti airtel", "bharti"],
  airtel:         ["bharti airtel", "airtel"],
  infy:           ["infosys", "infy"],
  infosys:        ["infosys"],
  icicibank:      ["icici bank"],
  icici:          ["icici"],
  kotakbank:      ["kotak mahindra bank", "kotak"],
  kotak:          ["kotak mahindra", "kotak"],
  "l&t":          ["larsen", "l&t"],
  lt:             ["larsen", "l&t"],
  larsen:         ["larsen", "l&t"],
  hindunilvr:     ["hindustan unilever", "hul"],
  hul:            ["hindustan unilever", "hul"],
  sbin:           ["state bank of india", "sbi"],
  sbi:            ["state bank of india", "sbi"],
  bajfinance:     ["bajaj finance"],
  axisbank:       ["axis bank"],
  axis:           ["axis bank"],
  asianpaint:     ["asian paints"],
  wipro:          ["wipro"],
  maruti:         ["maruti suzuki", "maruti"],
  nestleind:      ["nestle india", "nestle"],
  nestle:         ["nestle india", "nestle"],
  sunpharma:      ["sun pharmaceutical", "sun pharma"],
  titan:          ["titan company", "titan"],
  ultracemco:     ["ultratech cement", "ultracemco"],
  ongc:           ["oil and natural gas", "ongc"],
  ntpc:           ["ntpc"],
  hcltech:        ["hcl technologies", "hcl tech"],
  hcl:            ["hcl technologies", "hcl"],
  powergrid:      ["power grid corporation", "powergrid"],
  coalindia:      ["coal india"],
  techm:          ["tech mahindra", "techm"],
  adanient:       ["adani enterprises"],
  adani:          ["adani"],
  bajajfinsv:     ["bajaj finserv"],
  tatamotors:     ["tata motors"],
  drreddy:        ["dr. reddy", "dr reddy"],
  "dr reddy":     ["dr. reddy", "dr reddy"],
  drreddy_s:      ["dr. reddy", "dr reddy"],
  hindalco:       ["hindalco industries", "hindalco"],
  jswsteel:       ["jsw steel"],
  tatasteel:      ["tata steel"],
  grasim:         ["grasim industries", "grasim"],
  cipla:          ["cipla"],
  eichermot:      ["eicher motors"],
  eicher:         ["eicher motors"],
  heromotoco:     ["hero motocorp", "hero moto"],
  hero:           ["hero motocorp"],
  britannia:      ["britannia industries", "britannia"],
  divislab:       ["divi's laboratories", "divis", "divi"],
  divis:          ["divi's laboratories", "divis"],
  apollohosp:     ["apollo hospitals", "apollo"],
  apollo:         ["apollo"],
  bpcl:           ["bharat petroleum", "bpcl"],
  tataconsum:     ["tata consumer", "tata consumer products"],
  upl:            ["upl"],
  sbilife:        ["sbi life insurance", "sbi life"],
  "bajaj-auto":   ["bajaj auto"],
  bajajauto:      ["bajaj auto"],
  hdfclife:       ["hdfc life insurance", "hdfc life"],
  icicigi:        ["icici lombard"],
  "m&m":          ["mahindra & mahindra", "mahindra"],
  mm:             ["mahindra & mahindra", "mahindra"],
  mahindra:       ["mahindra"],
  adaniports:     ["adani ports", "adani port"],
  itc:            ["itc"],
  ltim:           ["ltimindtree", "mindtree"],
  ltimindtree:    ["ltimindtree", "mindtree"],

  // ── Nifty Next 50 ────────────────────────────────────────────────────────
  dmart:          ["avenue supermarts", "dmart"],
  avenue:         ["avenue supermarts"],
  siemens:        ["siemens india", "siemens"],
  havells:        ["havells india", "havells"],
  zomato:         ["zomato"],
  nykaa:          ["fsn e-commerce", "nykaa"],
  fsn:            ["fsn e-commerce", "nykaa"],
  paytm:          ["one 97 communications", "paytm"],
  pidilitind:     ["pidilite industries", "pidilite"],
  pidilite:       ["pidilite industries", "pidilite"],
  dabur:          ["dabur india", "dabur"],
  godrejcp:       ["godrej consumer products", "godrej consumer"],
  godrej:         ["godrej"],
  marico:         ["marico"],
  bergepaint:     ["berger paints", "berger"],
  muthootfin:     ["muthoot finance", "muthoot"],
  muthoot:        ["muthoot finance", "muthoot"],
  shreecem:       ["shree cement"],
  ambujacem:      ["ambuja cements", "ambuja"],
  ambuja:         ["ambuja cements", "ambuja"],
  adanigreen:     ["adani green energy", "adani green"],
  atgl:           ["adani total gas"],
  icicipru:       ["icici prudential life", "icici prudential"],
  srf:            ["srf"],
  indusindbk:     ["indusind bank", "indusind"],
  indusind:       ["indusind bank"],
  federalbnk:     ["federal bank"],
  federal:        ["federal bank"],
  idfcfirstb:     ["idfc first bank", "idfc"],
  idfc:           ["idfc first bank", "idfc"],
  bandhanbnk:     ["bandhan bank", "bandhan"],
  bandhan:        ["bandhan bank"],
  rblbank:        ["rbl bank"],
  yesbank:        ["yes bank"],
  canarabank:     ["canara bank"],
  canara:         ["canara bank"],
  unionbank:      ["union bank of india", "union bank"],
  pnb:            ["punjab national bank", "pnb"],
  bob:            ["bank of baroda"],
  bankofbaroda:   ["bank of baroda"],
  iob:            ["indian overseas bank", "iob"],
  boi:            ["bank of india"],
  centralbk:      ["central bank of india"],
  mahabank:       ["bank of maharashtra"],
  ucobank:        ["uco bank"],
  indianb:        ["indian bank"],

  // ── IT & Tech ─────────────────────────────────────────────────────────────
  mphasis:        ["mphasis"],
  coforge:        ["coforge"],
  ltts:           ["l&t technology services", "l&t tech"],
  persistent:     ["persistent systems"],
  hexaware:       ["hexaware technologies", "hexaware"],
  cyient:         ["cyient"],
  kpittech:       ["kpit technologies", "kpit"],
  kpit:           ["kpit technologies"],
  tataelxsi:      ["tata elxsi"],
  zensar:         ["zensar technologies", "zensar"],
  niit:           ["niit technologies", "niit"],
  rategain:       ["rategain travel", "rategain"],
  route:          ["route mobile"],
  tanla:          ["tanla platforms"],
  mastek:         ["mastek"],
  birlasoft:      ["birlasoft"],
  majesco:        ["majesco"],
  intellect:      ["intellect design", "intellect"],
  ramcosys:       ["ramco systems"],
  oracle:         ["oracle financial", "oracle"],
  firstsource:    ["firstsource solutions", "firstsource"],
  eclerx:         ["eclerx services"],
  infoedge:       ["info edge", "naukri"],
  naukri:         ["info edge", "naukri"],

  // ── Pharma & Healthcare ───────────────────────────────────────────────────
  auropharma:     ["aurobindo pharma", "aurobindo"],
  aurobindo:      ["aurobindo pharma"],
  lupin:          ["lupin"],
  torntpharm:     ["torrent pharmaceuticals", "torrent pharma"],
  torrent:        ["torrent"],
  alkem:          ["alkem laboratories", "alkem"],
  abbotindia:     ["abbott india", "abbott"],
  abbott:         ["abbott india"],
  pfizer:         ["pfizer india", "pfizer"],
  glenmark:       ["glenmark pharmaceuticals", "glenmark"],
  biocon:         ["biocon"],
  natcopharm:     ["natco pharma"],
  ipcalab:        ["ipca laboratories", "ipca"],
  ajantpharm:     ["ajanta pharma", "ajanta"],
  lauruslabs:     ["laurus labs", "laurus"],
  granules:       ["granules india"],
  syngene:        ["syngene international", "syngene"],
  suven:          ["suven pharmaceuticals"],
  jbchepharm:     ["jb chemicals", "jb pharma"],
  glaxo:          ["gsk pharmaceuticals", "glaxosmithkline", "glaxo"],
  gsk:            ["gsk pharmaceuticals", "glaxosmithkline"],
  novartis:       ["novartis india", "novartis"],
  sanofi:         ["sanofi india", "sanofi"],
  aavas:          ["aavas financiers"],
  concord:        ["concord biotech"],
  zydus:          ["zydus lifesciences", "zydus"],
  eris:           ["eris lifesciences"],
  indoco:         ["indoco remedies"],
  solara:         ["solara active pharma"],
  sudarshan:      ["sudarshan chemical"],
  sequent:        ["sequent scientific"],

  // ── Auto & Auto Ancillaries ───────────────────────────────────────────────
  ashokley:       ["ashok leyland"],
  ashok:          ["ashok leyland"],
  tvsmotor:       ["tvs motor company", "tvs motor"],
  tvs:            ["tvs motor", "tvs"],
  balkrisind:     ["balkrishna industries", "bkt"],
  balkrishna:     ["balkrishna industries"],
  motherson:      ["samvardhana motherson", "motherson"],
  endurance:      ["endurance technologies"],
  sundrmfast:     ["sundram fasteners"],
  apollotyre:     ["apollo tyres"],
  mrf:            ["mrf"],
  ceatltd:        ["ceat"],
  ceat:           ["ceat"],
  jktyre:         ["jk tyre"],
  exideind:       ["exide industries", "exide"],
  amarajabat:     ["amara raja batteries", "amara raja"],
  amaraja:        ["amara raja"],
  boschltd:       ["bosch india", "bosch"],
  bosch:          ["bosch india", "bosch"],
  schaeffler:     ["schaeffler india"],
  timken:         ["timken india"],
  skfindia:       ["skf india"],
  gabriel:        ["gabriel india"],
  suprajit:       ["suprajit engineering"],
  minda:          ["minda industries"],
  mindacorp:      ["minda corporation"],
  finolex:        ["finolex cables", "finolex"],
  rane:           ["rane holdings", "rane"],
  rico:           ["rico auto"],
  fag:            ["schaeffler india"],
  subros:         ["subros"],
  swarajeng:      ["swaraj engines"],
  swaraj:         ["swaraj engines"],
  wabco:          ["wabco india"],

  // ── FMCG & Consumer ───────────────────────────────────────────────────────
  colpal:         ["colgate-palmolive", "colgate"],
  colgate:        ["colgate-palmolive", "colgate"],
  emamiltd:       ["emami"],
  emami:          ["emami"],
  hatsun:         ["hatsun agro"],
  radico:         ["radico khaitan"],
  varunbev:       ["varun beverages"],
  devyani:        ["devyani international"],
  westlife:       ["westlife foodworld"],
  jublfood:       ["jubilant foodworks"],
  jubilant:       ["jubilant"],
  venkeys:        ["venky's india", "venky"],
  krbl:           ["krbl", "india gate"],
  ltfoods:        ["lt foods"],
  patanjali:      ["patanjali foods"],
  cclproduct:     ["ccl products"],
  agro:           ["agro tech"],
  tatachemical:   ["tata chemicals"],
  tatachem:       ["tata chemicals"],
  ghcl:           ["ghcl"],
  jyothylab:      ["jyothy laboratories", "jyothy labs"],
  bajajcon:       ["bajaj consumer care"],
  vip:            ["vip industries"],
  safari:         ["safari industries"],
  relaxo:         ["relaxo footwears"],
  bata:           ["bata india"],
  khadim:         ["khadim india"],

  // ── Chemicals ─────────────────────────────────────────────────────────────
  deepaknis:      ["deepak nitrite"],
  deepak:         ["deepak nitrite", "deepak fertilisers"],
  fineorg:        ["fine organic industries"],
  galaxysurf:     ["galaxy surfactants"],
  navinfluor:     ["navin fluorine"],
  aarti:          ["aarti industries"],
  vinati:         ["vinati organics"],
  nocil:          ["nocil"],
  gsfc:           ["gujarat state fertilizers", "gsfc"],
  gnfc:           ["gujarat narmada", "gnfc"],
  chamblfert:     ["chambal fertilisers"],
  chambal:        ["chambal fertilisers"],
  coromandel:     ["coromandel international"],
  rallis:         ["rallis india"],
  bayer:          ["bayer cropscience", "bayer"],
  sumitomo:       ["sumitomo chemical india"],
  basf:           ["basf india"],
  atul:           ["atul"],
  kansaipaint:    ["kansai nerolac", "kansai"],
  nerolac:        ["kansai nerolac"],
  akzonoble:      ["akzo nobel india"],
  clean:          ["clean science"],
  anupam:         ["anupam rasayan"],
  rossari:        ["rossari biotech"],
  aartisurf:      ["aarti surfactants"],

  // ── Infrastructure & Real Estate ──────────────────────────────────────────
  dlf:            ["dlf"],
  godrejprop:     ["godrej properties"],
  oberoirlty:     ["oberoi realty"],
  prestige:       ["prestige estates"],
  brigade:        ["brigade enterprises"],
  sobha:          ["sobha"],
  mahlife:        ["mahindra lifespace"],
  phoenixltd:     ["phoenix mills", "phoenix"],
  lodha:          ["macrotech developers", "lodha"],
  macrotech:      ["macrotech developers"],
  nesco:          ["nesco"],
  koltepatil:     ["kolte-patil", "kolte patil"],
  sunteck:        ["sunteck realty"],
  puravankara:    ["puravankara"],
  arvind:         ["arvind"],
  arvindsmart:    ["arvind smartspaces"],
  mahindralife:   ["mahindra lifespace"],
  cg:             ["cg power", "crompton greaves"],
  cgpower:        ["cg power and industrial"],
  cumminsind:     ["cummins india"],
  cummins:        ["cummins india"],
  thermax:        ["thermax"],
  bhel:           ["bharat heavy electricals", "bhel"],
  voltas:         ["voltas"],
  bluestar:       ["blue star"],
  whirlpool:      ["whirlpool of india"],
  kajariacer:     ["kajaria ceramics"],
  kajaria:        ["kajaria ceramics"],
  vguard:         ["v-guard industries", "vguard"],
  bajajelec:      ["bajaj electricals"],
  crompton:       ["crompton greaves consumer"],
  orientelec:     ["orient electric"],
  dixon:          ["dixon technologies"],
  amber:          ["amber enterprises"],
  pgel:           ["pg electroplast"],

  // ── Power & Energy ────────────────────────────────────────────────────────
  tatapower:      ["tata power"],
  adanipower:     ["adani power"],
  torntpower:     ["torrent power"],
  cesc:           ["cesc"],
  nhpc:           ["nhpc"],
  sjvn:           ["sjvn"],
  ireda:          ["indian renewable energy development", "ireda"],
  rpower:         ["reliance power"],
  jppower:        ["jaiprakash power"],
  jswenergy:      ["jsw energy"],

  // ── Telecom & Media ───────────────────────────────────────────────────────
  idea:           ["vodafone idea"],
  vodafone:       ["vodafone idea"],
  tatacomm:       ["tata communications"],
  hfcl:           ["hfcl"],
  stltech:        ["sterlite technologies"],
  sterlite:       ["sterlite technologies"],
  zeel:           ["zee entertainment", "zee"],
  zee:            ["zee entertainment"],
  suntv:          ["sun tv network", "sun tv"],
  pvrinox:        ["pvr inox", "pvr"],
  pvr:            ["pvr inox", "pvr"],
  inox:           ["inox"],
  saregama:       ["saregama india"],
  tips:           ["tips industries"],
  shemaroo:       ["shemaroo entertainment"],
  balaji:         ["balaji telefilms"],

  // ── Oil & Gas ─────────────────────────────────────────────────────────────
  ioc:            ["indian oil corporation", "ioc"],
  indianoil:      ["indian oil corporation"],
  mgl:            ["mahanagar gas"],
  igl:            ["indraprastha gas", "igl"],
  gujgasltd:      ["gujarat gas"],
  gujaratgas:     ["gujarat gas"],
  petronet:       ["petronet lng", "petronet"],
  castrolind:     ["castrol india", "castrol"],
  castrol:        ["castrol india"],
  aegischem:      ["aegis logistics"],
  aegis:          ["aegis logistics"],
  gulfoillub:     ["gulf oil lubricants", "gulf oil"],
  gulfoil:        ["gulf oil lubricants"],

  // ── Metals & Mining ───────────────────────────────────────────────────────
  vedl:           ["vedanta"],
  vedanta:        ["vedanta"],
  nmdc:           ["nmdc"],
  nationalum:     ["national aluminium", "nalco"],
  nalco:          ["national aluminium", "nalco"],
  hindcopper:     ["hindustan copper"],
  moil:           ["moil"],
  aplapollo:      ["apl apollo tubes", "apl apollo"],
  jindalsaw:      ["jindal saw"],
  jspl:           ["jindal steel and power", "jindal steel"],
  jindal:         ["jindal"],
  welcorp:        ["welspun corp"],
  welspun:        ["welspun"],
  ratnamani:      ["ratnamani metals"],
  kalyanisteel:   ["kalyani steels"],
  electrosteel:   ["electrosteel castings"],
  sail:           ["steel authority of india", "sail"],
  ismt:           ["ismt"],
  tin:            ["tinplate company"],
  tinsec:         ["tin sector"],

  // ── Cement ────────────────────────────────────────────────────────────────
  jkcement:       ["jk cement"],
  jklakshmi:      ["jk lakshmi cement"],
  ramcocem:       ["the ramco cements", "ramco cements"],
  ramco:          ["ramco cements", "ramco"],
  dalmiacem:      ["dalmia bharat", "dalmia cement"],
  dalmia:         ["dalmia bharat"],
  prism:          ["prism johnson"],
  orientcem:      ["orient cement"],
  sagcem:         ["sagar cements"],
  starcem:        ["star cement"],
  birlacorpn:     ["birla corporation"],
  heidel:         ["nuvoco vistas", "heidelbergcement"],
  nuvoco:         ["nuvoco vistas"],
  jkpaper:        ["jk paper"],
  tnpl:           ["tamil nadu newsprint", "tnpl"],

  // ── Insurance ────────────────────────────────────────────────────────────
  starhealth:     ["star health and allied insurance", "star health"],
  godigit:        ["go digit general insurance"],
  niacl:          ["new india assurance"],
  lic:            ["life insurance corporation", "lic"],
  licif:          ["life insurance corporation", "lic"],
  iciciagi:       ["icici lombard general insurance"],
  sbicard:        ["sbi cards and payment services", "sbi card"],
  maxlife:        ["max financial services", "max life"],
  maxfin:         ["max financial services"],

  // ── Finance / NBFC / MFI ─────────────────────────────────────────────────
  bajajhldng:     ["bajaj holdings"],
  cholafin:       ["cholamandalam finance", "chola"],
  chola:          ["cholamandalam"],
  mmfsl:          ["mahindra & mahindra financial", "mahindra finance"],
  mahindfin:      ["mahindra & mahindra financial"],
  shriramfin:     ["shriram finance"],
  shriram:        ["shriram"],
  lichsgfin:      ["lic housing finance", "lic hfl"],
  pnbhousing:     ["pnb housing finance"],
  repco:          ["repco home finance"],
  canfinhome:     ["can fin homes"],
  aadharhfc:      ["aadhar housing finance"],
  homefirst:      ["home first finance"],
  aptus:          ["aptus value housing"],
  edelweiss:      ["edelweiss financial"],
  motilalofs:     ["motilal oswal financial", "motilal oswal"],
  motilal:        ["motilal oswal"],
  iiflwam:        ["iifl wealth management", "iifl"],
  iifl:           ["iifl"],
  angelone:       ["angel one"],
  icicisec:       ["icici securities"],
  jmfinancil:     ["jm financial"],
  manappuram:     ["manappuram finance"],
  masfin:         ["mas financial services"],
  creditacc:      ["creditaccess grameen"],
  spandana:       ["spandana sphoorty"],
  ujjivan:        ["ujjivan financial", "ujjivan small finance"],
  equitas:        ["equitas small finance"],
  suryoday:       ["suryoday small finance"],
  utkarsh:        ["utkarsh small finance"],
  fincare:        ["fincare small finance"],
  esafsfb:        ["esaf small finance"],
  nuvama:         ["nuvama wealth"],
  "360one":       ["360 one wam", "360one"],
  anandrath:      ["anand rathi wealth", "anand rathi"],
  anandrathi:     ["anand rathi wealth", "anand rathi"],
  hdfcamc:        ["hdfc asset management", "hdfc amc"],
  nipponamcl:     ["nippon india mutual fund", "nippon amc"],
  abslamc:        ["aditya birla sun life amc"],
  uti:            ["uti asset management"],
  nambiamc:       ["360 one wam"],
  groww:          ["groww"],

  // ── Railways & Defence ────────────────────────────────────────────────────
  irfc:           ["indian railway finance corporation", "irfc"],
  irctc:          ["indian railway catering and tourism", "irctc"],
  rvnl:           ["rail vikas nigam", "rvnl"],
  nbcc:           ["nbcc (india)", "nbcc"],
  bel:            ["bharat electronics", "bel"],
  hal:            ["hindustan aeronautics", "hal"],
  beml:           ["beml"],
  grse:           ["garden reach shipbuilders", "grse"],
  cochinship:     ["cochin shipyard"],
  mdl:            ["mazagon dock"],
  ircon:          ["ircon international"],
  rites:          ["rites"],
  railtel:        ["railtel corporation"],
  texmaco:        ["texmaco rail"],
  titagarh:       ["titagarh rail systems"],
  cochin:         ["cochin shipyard"],
  mazagon:        ["mazagon dock"],

  // ── Logistics & Shipping ─────────────────────────────────────────────────
  concor:         ["container corporation of india", "concor"],
  bluedart:       ["blue dart express", "blue dart"],
  delhivery:      ["delhivery"],
  gati:           ["gati"],
  vrl:            ["vrl logistics"],
  tciexp:         ["transport corporation of india", "tci express"],
  allcargo:       ["allcargo logistics"],
  mahlog:         ["mahindra logistics"],
  redington:      ["redington india"],
  ships:          ["shipping corporation", "sciindia"],
  sci:            ["shipping corporation"],
  gangotri:       ["gangotri textiles"],
  seamecltd:      ["seamec"],

  // ── Textile & Apparel ─────────────────────────────────────────────────────
  welspuntex:     ["welspun india"],
  trident:        ["trident"],
  vardhman:       ["vardhman textiles"],
  kitex:          ["kitex garments"],
  nitin:          ["nitin spinners"],
  alok:           ["alok industries"],
  siyaram:        ["siyaram silk mills"],
  raymond:        ["raymond"],
  mafatlal:       ["mafatlal industries"],
  pageind:        ["page industries"],

  // ── Hospitality & Travel ──────────────────────────────────────────────────
  ihcl:           ["indian hotels", "taj hotels"],
  indianhotels:   ["indian hotels", "taj hotels"],
  taj:            ["indian hotels", "taj hotels"],
  eih:            ["eih (oberoi)", "oberoi"],
  oberoi:         ["eih (oberoi)"],
  lemon:          ["lemon tree hotels"],
  chalet:         ["chalet hotels"],
  mahindrahol:    ["mahindra holidays"],
  interglobe:     ["interglobe aviation", "indigo"],
  indigo:         ["interglobe aviation", "indigo"],
  spicejet:       ["spicejet"],
  airasia:        ["air asia"],
  easemytrip:     ["easy trip planners", "easemytrip"],
  thomascook:     ["thomas cook india"],
  cox:            ["cox & kings"],
  mktourism:      ["mahindra holidays"],

  // ── Agriculture & Food Processing ────────────────────────────────────────
  uflex:          ["uflex"],
  avantifeed:     ["avanti feeds"],
  waterbase:      ["waterbase"],
  godrejagro:     ["godrej agrovet"],
  eidparry:       ["eid parry"],
  kisanmoulding:  ["kisan mouldings"],
  kaveri:         ["kaveri seed"],
  jain:           ["jain irrigation"],
  mahkseeds:      ["mahyco"],

  // ── Diversified & Others ─────────────────────────────────────────────────
  abcapital:      ["aditya birla capital", "aditya birla"],
  aditya:         ["aditya birla"],
  birla:          ["aditya birla", "birla"],
  tatainvest:     ["tata investment corporation"],
  piramal:        ["piramal enterprises", "piramal"],
  wockhardt:      ["wockhardt"],
  trent:          ["trent"],
  abfrl:          ["aditya birla fashion", "pantaloons"],
  pantaloons:     ["aditya birla fashion", "pantaloons"],
  shoppers:       ["shoppers stop"],
  vcustomer:      ["vcustomer services"],
  tcns:           ["tcns clothing"],
  go:             ["go fashion"],
  gofashion:      ["go fashion"],
  vedant:         ["vedant fashions", "manyavar"],
  manyavar:       ["vedant fashions", "manyavar"],
  metro:          ["metro brands"],
  metrobrands:    ["metro brands"],
  kalyanjewel:    ["kalyan jewellers", "kalyan"],
  senco:          ["senco gold"],
  pcjeweller:     ["pc jeweller"],
  rajeshexpo:     ["rajesh exports"],
  goldiam:        ["goldiam international"],

  // ── Micro Finance & Small Finance ────────────────────────────────────────
  arohan:         ["arohan financial services"],
  satin:          ["satin creditcare network"],
  fusion:         ["fusion micro finance"],
  asianbmb:       ["asian market corporation"],
  chaitanya:      ["chaitanya india"],

  // ── Real Estate Investment Trusts ────────────────────────────────────────
  embassy:        ["embassy office parks"],
  mindspace:      ["mindspace business parks"],
  brookfield:     ["brookfield india real estate"],
  nexus:          ["nexus select trust"],

  // ── Miscellaneous ─────────────────────────────────────────────────────────
  kec:            ["kec international"],
  kalpataru:      ["kalpataru projects", "kalpataru"],
  pnc:            ["pnc infratech"],
  itdcem:         ["itd cementation"],
  hg:             ["hindustan construction", "hcc"],
  hcc:            ["hindustan construction", "hcc"],
  dilipbuildcon:  ["dilip buildcon"],
  irb:            ["irb infrastructure"],
  ashoka:         ["ashoka buildcon"],
  sadbhav:        ["sadbhav engineering"],
  ahluwalia:      ["ahluwalia contracts"],
  knrcon:         ["knr constructions"],
  psp:            ["psp projects"],
  hle:            ["hle glascoat"],
  gmrairport:     ["gmr airports infrastructure"],
  adaniairport:   ["adani airports"],
  gvkpower:       ["gvk power"],
  spl:            ["standard glass lining"],
  fdc:            ["fdc"],
  glfl:           ["gujarat lease financing"],
  carysil:        ["carysil"],
  shankara:       ["shankara building products"],
  hikal:          ["hikal"],
  igarashi:       ["igarashi motors"],
  mold:           ["mold-tek packaging"],
  kpil:           ["kalpataru projects"],
};

/**
 * Expands a raw search string into all terms to match against feed items.
 * Always includes the original term; adds alias expansions when found.
 */
export function expandSearch(raw: string): string[] {
  const term = raw.trim().toLowerCase();
  const aliases = COMPANY_ALIASES[term];
  return aliases ? [...new Set([term, ...aliases])] : [term];
}
